[package]
name = "libcosmic"
version = "0.1.0"
edition = "2021"

[dependencies]
cascade = "1"
gdk4 = "0.3.1"
gdk4-x11 = "0.3.0"
gio = "0.14.8"
gtk4 = "0.3.1"
x11 = { version = "2", features = ["xlib"] }

# examples/launcher
#pop-launcher = "1.0.3"
pop-launcher = { git = "https://github.com/pop-os/launcher", branch = "master" }
serde_json = "1.0.72"
pop-launcher-service = { git = "https://github.com/pop-os/launcher", branch = "master" }
postage = "0.4.1"
futures = "0.3.18"
glib = "0.14.8"
# examples/gtklauncher
once_cell = "1.8.0"
xdg = "2.4.0"
serde = "1.0.130"
x11rb = "0.9.0"
