[package]
name = "libcosmic"
version = "0.1.0"
edition = "2021"

[lib]
name = "cosmic"

[dependencies]
freedesktop-icons = "0.2.1"

[dependencies.iced]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
features = ["cosmic_theme", "svg"]

[dependencies.iced_native]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
features = ["cosmic_theme"]

[workspace]
members = [
  "examples/cosmic",
  "gtk4",
  "gtk4/widgets"
]
