[package]
name = "libcosmic"
version = "0.1.0"
edition = "2021"

[dependencies]
cascade = "1.0.0"
derivative = { version = "2", optional = true }
gtk4 = { git = "https://github.com/gtk-rs/gtk4-rs", features = ["v4_4"] }
gdk4 = { git = "https://github.com/gtk-rs/gtk4-rs" }
gdk4-wayland = { git = "https://github.com/gtk-rs/gtk4-rs", features = ["wayland_crate"], optional = true }
gdk4-x11 = { git = "https://github.com/gtk-rs/gtk4-rs", features = ["xlib"] }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core" }
gobject-sys = { git = "https://github.com/gtk-rs/gtk-rs-core" }
wayland-client = { version = "0.29.4", optional = true }
wayland-protocols = { version = "0.29.4", features = ["client", "unstable_protocols"], optional = true }
x11 = { version = "2.19.1", features = ["xlib"] }
once_cell = "1.9.0"
libcosmic-widgets = { path = "widgets" }

[features]
layer-shell = ["derivative", "gdk4-wayland", "wayland-client", "wayland-protocols"]

[workspace]
members = ["widgets"]
