[package]
name = "libcosmic"
version = "0.1.0"
edition = "2021"

[dependencies]
cascade = "1"
derivative = "2"
gdk4 = "0.3.1"
gdk4-wayland = { version = "0.3", optional = true }
gdk4-x11 = "0.3.0"
gio = "0.14.8"
gobject-sys = "0.14.0"
wayland-client = { version = "0.28", optional = true }
wayland-protocols = { version = "0.28", features = [ "client", "unstable_protocols" ], optional = true }
x11 = { version = "2", features = ["xlib"] }

# examples
gtk4 = { version ="0.3.1", features = ["v4_4"] }
glib-sys = "0.14.0"
relm4-macros = { git = "https://github.com/AaronErhardt/Relm4" }
pop-launcher-service = { git = "https://github.com/wash2/launcher.git" }
pop-launcher = { git = "https://github.com/wash2/launcher.git" }
serde = "1.0.130"
serde_json = "1.0.72"
tokio = { version = "1.15.0", features = ["sync"] }
futures = "0.3.17"
futures-util = "0.3.19"
once_cell = "1.8.0"
xdg = "2.4.0"
x11rb = "0.9.0"
# zbus
zbus = "2.0.0"
zvariant = "3.0.0"
zvariant_derive = "3.0.0"
libloading = "0.7.2"
gtk4-sys = "0.3.1"

[profile.release]
incremental = true
debug = 1

[features]
layer-shell = ["gdk4-wayland", "wayland-client", "wayland-protocols"]
