[package]
name = "libcosmic"
version = "0.1.0"
edition = "2021"

[lib]
name = "cosmic"

[features]
default = []
debug = ["iced/debug"]

[dependencies]
freedesktop-icons = "0.2.1"

[dependencies.iced]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
#path = "../iced"
features = ["cosmic-theme", "svg"]

[dependencies.iced_native]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
#path = "../iced/native"
features = ["cosmic-theme"]

[dependencies.iced_lazy]
git = "https://github.com/pop-os/iced.git"
branch = "cosmic-design-system"
#path = "../iced/lazy"

[workspace]
members = [
  "examples/cosmic",
  "gtk4",
  "gtk4/widgets"
]
