[package]
name = "text"
version = "0.1.0"
authors = []
edition = "2021"
publish = false

[dependencies]
orbclient = "0.3"
rusttype = "0.9"
rustybuzz = "0.5"
unicode-bidi = "0.3"
unicode-script = "0.5"

[features]
default = []
mono = []
